[tool.poetry]
name = "netapp"
version = "0.1.0"
description = ""
authors = ["Sean Rowe <sean@seanrowe.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.109.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
